"""init models

Revision ID: c95f7799a9e1
Revises: 
Create Date: 2026-02-03 16:43:40.564128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95f7799a9e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('video_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('views_count', sa.BigInteger(), nullable=False),
    sa.Column('likes_count', sa.BigInteger(), nullable=False),
    sa.Column('comments_count', sa.BigInteger(), nullable=False),
    sa.Column('reports_count', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_videos_creator_date', 'videos', ['creator_id', 'video_created_at'], unique=False)
    op.create_index('idx_videos_date_views', 'videos', ['video_created_at', 'views_count'], unique=False)
    op.create_index(op.f('ix_videos_creator_id'), 'videos', ['creator_id'], unique=False)
    op.create_index(op.f('ix_videos_video_created_at'), 'videos', ['video_created_at'], unique=False)
    op.create_table('video_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('views_count', sa.BigInteger(), nullable=False),
    sa.Column('likes_count', sa.BigInteger(), nullable=False),
    sa.Column('comments_count', sa.BigInteger(), nullable=False),
    sa.Column('reports_count', sa.BigInteger(), nullable=False),
    sa.Column('delta_views_count', sa.BigInteger(), nullable=False),
    sa.Column('delta_likes_count', sa.BigInteger(), nullable=False),
    sa.Column('delta_comments_count', sa.BigInteger(), nullable=False),
    sa.Column('delta_reports_count', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshots_date_video', 'video_snapshots', ['created_at', 'video_id'], unique=False)
    op.create_index(op.f('ix_video_snapshots_created_at'), 'video_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_video_snapshots_video_id'), 'video_snapshots', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_snapshots_video_id'), table_name='video_snapshots')
    op.drop_index(op.f('ix_video_snapshots_created_at'), table_name='video_snapshots')
    op.drop_index('idx_snapshots_date_video', table_name='video_snapshots')
    op.drop_table('video_snapshots')
    op.drop_index(op.f('ix_videos_video_created_at'), table_name='videos')
    op.drop_index(op.f('ix_videos_creator_id'), table_name='videos')
    op.drop_index('idx_videos_date_views', table_name='videos')
    op.drop_index('idx_videos_creator_date', table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
